[book]
authors = ["Luke Maxwell", "Sean Tao"]
language = "en"
src = "src"
title = "1757 Programming Documentation"

[output.html]
git-repository-url = "https://github.com/1757WestwoodRobotics/prog-docs"
additional-js = ["coi.js"]


[preprocessor.repl]
# iframe url, default is https://mr-addict.github.io/mdbook-repl/embed/
# src = "https://lmaxwell24.github.io/mdbook-repl/embed/"
src = "https://whsrobotics.org/mdbook-repl/embed/"

# python is disabled by default and loading is lazy
python.enable = true
python.loading = "lazy"


[preprocessor.github-authors]
